//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICP.BBDD
{
    using System;
    using System.Collections.Generic;
    
    public partial class NSERIES_SEGUIMIENTO
    {
        public int ID { get; set; }
        public int PEDIDO_ID { get; set; }
        public int LINEA_ID { get; set; }
        public string NUMERO_SERIE { get; set; }
        public Nullable<System.DateTime> FECHA_REGISTRO { get; set; }
        public string USUARIO { get; set; }
        public string PETICION { get; set; }
        public string REFERENCIA { get; set; }
        public Nullable<int> PALET { get; set; }
    
        public virtual PALET PALET1 { get; set; }
    }
}
