//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICP.BBDD
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDEN_SALIDA_CAB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ORDEN_SALIDA_CAB()
        {
            this.ORDEN_SALIDA_LIN = new HashSet<ORDEN_SALIDA_LIN>();
        }
    
        public int PETICION { get; set; }
        public string PEDIDO_CLIENTE { get; set; }
        public string CODIGO_CLIENTE { get; set; }
        public System.DateTime F_CREACION { get; set; }
        public string NOMBRE_CLIENTE { get; set; }
        public string DIRECCION_ENTREGA { get; set; }
        public string CODIGO_POSTAL { get; set; }
        public string POBLACION { get; set; }
        public string PROVINCIA { get; set; }
        public string TELEFONO { get; set; }
        public int ESTATUS_PETICION { get; set; }
        public Nullable<System.DateTime> F_CONFIRMACION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDEN_SALIDA_LIN> ORDEN_SALIDA_LIN { get; set; }
    }
}
