//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICP.BBDD
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDEN_SALIDA_LIN
    {
        public int PETICION { get; set; }
        public int LINEA { get; set; }
        public string REFERENCIA { get; set; }
        public int CANTIDAD { get; set; }
        public Nullable<int> CANTIDAD_PICADA { get; set; }
    
        public virtual ORDEN_SALIDA_CAB ORDEN_SALIDA_CAB { get; set; }
        public virtual REFERENCIA REFERENCIA1 { get; set; }
    }
}
