//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICP.BBDD
{
    using System;
    using System.Collections.Generic;
    
    public partial class PALET
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PALET()
        {
            this.NSERIES_RECEPCIONES = new HashSet<NSERIES_RECEPCIONES>();
            this.NSERIES_SEGUIMIENTO = new HashSet<NSERIES_SEGUIMIENTO>();
        }
    
        public int PALET1 { get; set; }
        public string REFERENCIA { get; set; }
        public Nullable<int> CANTIDAD { get; set; }
        public string ALBARAN_RECEPCION { get; set; }
        public string UBICACION { get; set; }
        public int ESTATUS_PALET { get; set; }
        public Nullable<System.DateTime> F_INSERT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NSERIES_RECEPCIONES> NSERIES_RECEPCIONES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NSERIES_SEGUIMIENTO> NSERIES_SEGUIMIENTO { get; set; }
        public virtual RECEPCIONES_CAB RECEPCIONES_CAB { get; set; }
        public virtual REFERENCIA REFERENCIA1 { get; set; }
        public virtual UBICACIONE UBICACIONE { get; set; }
        public virtual REFERENCIA REFERENCIA2 { get; set; }
        public virtual UBICACIONE UBICACIONE1 { get; set; }
    }
}
