//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICP.BBDD
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECEPCIONES_LIN
    {
        public string ALBARAN { get; set; }
        public int LINEA { get; set; }
        public string REFERENCIA { get; set; }
        public int CANTIDAD { get; set; }
        public Nullable<int> CANTIDAD_BUENA { get; set; }
        public Nullable<int> CANTIDAD_MALA { get; set; }
        public string UBICACION { get; set; }
        public string NUMERO_SERIE { get; set; }
        public Nullable<int> PALETID { get; set; }
    
        public virtual RECEPCIONES_CAB RECEPCIONES_CAB { get; set; }
        public virtual REFERENCIA REFERENCIA1 { get; set; }
    }
}
