//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICP.BBDD
{
    using System;
    using System.Collections.Generic;
    
    public partial class REFERENCIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public REFERENCIA()
        {
            this.ORDEN_SALIDA_LIN = new HashSet<ORDEN_SALIDA_LIN>();
            this.PALETS = new HashSet<PALET>();
            this.PALETS1 = new HashSet<PALET>();
            this.RECEPCIONES_LIN = new HashSet<RECEPCIONES_LIN>();
        }
    
        public string REFERENCIA1 { get; set; }
        public string DES_REFERENCIA { get; set; }
        public Nullable<decimal> PRECIO { get; set; }
        public Nullable<System.DateTime> F_CREACION { get; set; }
        public string IMAGEN { get; set; }
        public bool LLEVA_N_SERIES { get; set; }
        public Nullable<int> LONGITUD_N_SERIE { get; set; }
        public bool ESTA_HABILITADA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDEN_SALIDA_LIN> ORDEN_SALIDA_LIN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PALET> PALETS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PALET> PALETS1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RECEPCIONES_LIN> RECEPCIONES_LIN { get; set; }
    }
}
