//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICP.BBDD
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_DETALLE_ALMACENAMIENTO_TABLAS
    {
        public string TABLA { get; set; }
        public string ESQUEMA { get; set; }
        public Nullable<long> FILAS { get; set; }
        public Nullable<int> TOTAL_MB { get; set; }
        public Nullable<int> LIBRE_MB { get; set; }
        public string PORCENTAJE_LIBRE { get; set; }
        public string COLUMNA { get; set; }
        public Nullable<int> ID_INDICE_COLUMNA { get; set; }
        public string NOMBRE_INDICE { get; set; }
        public string TIPO_INDICE { get; set; }
        public Nullable<bool> PK { get; set; }
        public Nullable<byte> NUM_COLUMNA { get; set; }
        public Nullable<bool> CLAVE_UNICA { get; set; }
        public Nullable<bool> INCLUIDA { get; set; }
        public string CAMPO_IDENTITY { get; set; }
        public string DATOS_GRUPO_FICHEROS { get; set; }
        public string DATOS_FICHERO { get; set; }
        public string DATOS_RUTA_FICHERO { get; set; }
        public string INDICES_GRUPO_FICHERO { get; set; }
        public string INDICES_FICHERO { get; set; }
        public string INDICES_RUTA_FICHERO { get; set; }
        public string LOB_GRUPO_FICHEROS { get; set; }
        public string LOB_FICHERO { get; set; }
        public string LOB_RUTA_FICHERO { get; set; }
    }
}
