//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICP.BBDD
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_DETALLE_FOREIGN_KEYS
    {
        public string NOM_FK { get; set; }
        public string TABLA { get; set; }
        public string ESQUEMA { get; set; }
        public string COLUMNA { get; set; }
        public string TABLA_REFERENCIA { get; set; }
        public string ESQUEMA_REFERENCIA { get; set; }
        public string COLUMNA_REFERENCIA { get; set; }
        public Nullable<byte> TIPO_BORRADO_EN_CASCADA { get; set; }
        public Nullable<byte> TIPO_ACTUALIZACION_EN_CASCADA { get; set; }
    }
}
