//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICP.BBDD
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_GRANT
    {
        public string USUARIO { get; set; }
        public string TIPO_PERMISO { get; set; }
        public string NOMBRE_PERMISO { get; set; }
        public string NOMBRE_OBJETO { get; set; }
        public string TIPO { get; set; }
        public string COLUMNA { get; set; }
        public string GRANT { get; set; }
        public string ESQUEMA { get; set; }
    }
}
