//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICP.BBDD
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_SQL
    {
        public int ID { get; set; }
        public string TIPO_OBJETO { get; set; }
        public string ESQUEMA { get; set; }
        public string TABLA { get; set; }
        public string CAMPO { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<int> POSICION { get; set; }
        public string TIPO { get; set; }
        public int DIMENSION { get; set; }
        public int PERMITE_NULOS { get; set; }
        public string DEFECTO { get; set; }
        public string CLAVE { get; set; }
        public string CLAVE_FK { get; set; }
        public string CLAVE_UQ { get; set; }
        public string CLAVE_CK { get; set; }
        public int INDICES { get; set; }
        public string COLLATE { get; set; }
        public string GRUPO_FICHEROS { get; set; }
        public Nullable<int> KBYTES { get; set; }
        public Nullable<int> MBYTES { get; set; }
        public Nullable<int> GROWTH { get; set; }
        public Nullable<int> N_FILES { get; set; }
        public string GRUPO { get; set; }
        public string TRIGGERS { get; set; }
        public string name { get; set; }
        public Nullable<int> object_id { get; set; }
        public Nullable<int> data_space_id { get; set; }
        public string FILEGROUP { get; set; }
    }
}
