//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICP.BBDD
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_SQL_FICHEROS
    {
        public string BBDD { get; set; }
        public string FICHERO { get; set; }
        public string RUTA_FICHERO { get; set; }
        public string GRUPO_FICHERO { get; set; }
        public Nullable<int> TOTAL_MB { get; set; }
        public Nullable<int> LIBRE_MB { get; set; }
        public Nullable<int> PORCENTAJE_LIBRE { get; set; }
    }
}
