//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICP.BBDD
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_SQL_TABLAS
    {
        public int ID { get; set; }
        public string TABLA { get; set; }
        public string CAMPO { get; set; }
        public Nullable<int> POSICION { get; set; }
        public string TIPO { get; set; }
        public Nullable<int> DIMENSION { get; set; }
    }
}
