//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICP.BBDD
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_SQL_INDICES_FRAGMENTACION
    {
        public string TABLA { get; set; }
        public string INDICE { get; set; }
        public string CAMPO { get; set; }
        public string TIPO_CLUSTER { get; set; }
        public byte FILL_FACTOR { get; set; }
        public string GRUPO_ARCHIVOS { get; set; }
        public double FRAGMENTACION { get; set; }
        public long NUM_PAGINAS { get; set; }
    }
}
