//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICP.BBDD
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_REFERENCIAS_STOCK
    {
        public string REFERENCIA { get; set; }
        public string DES_REFERENCIA { get; set; }
        public Nullable<decimal> PRECIO { get; set; }
        public Nullable<System.DateTime> F_CREACION { get; set; }
        public bool LLEVA_N_SERIES { get; set; }
        public Nullable<int> LONGITUD_N_SERIE { get; set; }
        public bool ESTA_HABILITADA { get; set; }
        public int STOCK_DISPONIBLE { get; set; }
    }
}
