//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICP.BBDD
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_STOCK_DISPONIBLE
    {
        public int ID { get; set; }
        public string REFERENCIA { get; set; }
        public Nullable<int> STOCK_DISPONIBLE { get; set; }
    }
}
